Fix export of `_zhuyin_get_zhuyin_string` in libzhuyin
There is an extra underscore in the symbol name
`_zhuyin_get_zhuyin_string` in libzhuyin's exported symbols list,
causing ld to complain:

    Undefined symbols for architecture arm64:
      "_zhuyin_get__zhuyin_string", referenced from:
          <initial-undefines>
    ld: symbol(s) not found for architecture arm64